### ISSUE TITLE
Spawn weapon by name broken

### ISSUE THREAD

**Issue by nerakhon** [Xmaught/xmau_AdminMenu#1]
When going into the weapon spawner menu, there is no way to pick the weapon by name. (Enter on the sub menu doesn't moe the focus down to pick the weapon).

**Comment by Xmaught** [comment]
im developing in c# for another core, this is an adaptation for redemrp and you can use it, but redemrp_core dont support at least for now any kind of input to write for c# languange, so you cant enter the name of the weapon.
If in the future they implement any way to do it work ill fix it, be sure of that

**Comment by Xmaught** [comment]
Closed cause for now is imposible to fix
